INSERT INTO [Client_TimeLimits]([_key],[OppExpire],[OppRestart],[OppDelay],[InterfaceTimeout],[ClientName],[IsPracticeTest],[sessionExpire],[requestInterfaceTimeout],[RefreshValueMultiplier])VALUES(newid(), 1, 10, -1, 15, N'SBAC', 0, 8, 120, 2)

INSERT TDS_TestToolType VALUES (N'American Sign Language', 1, 1, N'TDSAcc-ASL', 0, 0)
INSERT TDS_TestToolType VALUES (N'Audio Playback Controls', 1, 0, N'TDSAcc-AudioPlaybackControls', 0, 1)
INSERT TDS_TestToolType VALUES (N'Block Pausing', 1, 0, N'TDSAcc-BlockPausing', 0, 0)
INSERT TDS_TestToolType VALUES (N'Braille', 0, 1, N'TDSAcc-Braille', 0, 0)
INSERT TDS_TestToolType VALUES (N'Braille Type', 1, 1, N'TDSAcc-BrailleType', 0, 1)
INSERT TDS_TestToolType VALUES (N'Calculator', 0, 0, N'TDSAcc-Calculator', 0, 0)
INSERT TDS_TestToolType VALUES (N'Closed Captioning', 1, 1, N'TDSACC-NFCLOSEDCAP', 0, 1)
INSERT TDS_TestToolType VALUES (N'Color Choices', 1, 1, N'TDSAcc-ColorChoices', 0, 0)
INSERT TDS_TestToolType VALUES (N'Compass', 1, 1, N'TDSAcc-Compass', 0, 1)
INSERT TDS_TestToolType VALUES (N'Cover Pages', 1, 0, N'TDSAcc-CoverPages', 0, 0)
INSERT TDS_TestToolType VALUES (N'Dictionary', 1, 1, N'TDSAcc-Dictionary', 0, 1)
INSERT TDS_TestToolType VALUES (N'Dictionary Options', 1, 1, N'TDSAcc-DictionaryOptns', 0, 1)
INSERT TDS_TestToolType VALUES (N'Emboss', 1, 1, N'TDSAcc-Emboss', 0, 1)
INSERT TDS_TestToolType VALUES (N'Emboss Request Type', 1, 1, N'TDSAcc-EmbossRequestType', 0, 1)
INSERT TDS_TestToolType VALUES (N'Exempted Domains', 1, 1, N'TDSAcc-ExemptedDomains', 0, 0)
INSERT TDS_TestToolType VALUES (N'Expandable Passages', 1, 1, N'TDSAcc-ExpandablePassages', 0, 1)
INSERT TDS_TestToolType VALUES (N'Font Type', 0, 0, N'TDSAcc-FontType', 0, 0)
INSERT TDS_TestToolType VALUES (N'Formula', 0, 0, N'TDSAcc-Formula', 0, 0)
INSERT TDS_TestToolType VALUES (N'Fullscreen', 1, 0, N'TDSAcc-Fullscreen', 0, 0)
INSERT TDS_TestToolType VALUES (N'Global Notes', 1, 0, N'TDSAcc-GlobalNotes', 0, 0)
INSERT TDS_TestToolType VALUES (N'Guide for Revision', 0, 0, N'TDSAcc-GuideForRevision', 0, 0)
INSERT TDS_TestToolType VALUES (N'Hardware Checks', 1, 0, N'TDSAcc-HWCheck', 0, 0)
INSERT TDS_TestToolType VALUES (N'Highlight', 0, 0, N'TDSAcc-Highlight', 0, 0)
INSERT TDS_TestToolType VALUES (N'Item Font Size', 0, 0, N'TDSAcc-ItemFontSize', 0, 0)
INSERT TDS_TestToolType VALUES (N'Item Numbers', 1, 0, N'TDSAcc-ItemNumbers', 0, 0)
INSERT TDS_TestToolType VALUES (N'Item Response Reset', 1, 1, N'TDSAcc-ItemResponseReset', 0, 1)
INSERT TDS_TestToolType VALUES (N'Item Score Report', 1, 0, N'TDSAcc-ItemScoreReport', 0, 0)
INSERT TDS_TestToolType VALUES (N'Item Types Exclusion', 0, 1, N'TDSAcc-ItemTypesExclusion', 0, 1)
INSERT TDS_TestToolType VALUES (N'Language', 0, 1, N'TDSAcc-Language', 1, 1)
INSERT TDS_TestToolType VALUES (N'Line Reader', 1, 0, N'TDSAcc-LineReader', 0, 0)
INSERT TDS_TestToolType VALUES (N'Mark for Review', 0, 0, N'TDSAcc-MarkForReview', 0, 0)
INSERT TDS_TestToolType VALUES (N'Masking', 1, 1, N'TDSAcc-Masking', 0, 1)
INSERT TDS_TestToolType VALUES (N'Mute System Volume', 1, 0, N'TDSAcc-Mute', 0, 0)
INSERT TDS_TestToolType VALUES (N'Navigation Dropdown', 1, 0, N'TDSAcc-NavDrpDwn', 0, 0)
INSERT TDS_TestToolType VALUES (N'Offline Tester', 0, 1, N'TDSAcc-OfflineTester', 0, 0)
INSERT TDS_TestToolType VALUES (N'Paginate Item Groups', 1, 0, N'TDSAcc-PaginateItemGroups', 0, 1)
INSERT TDS_TestToolType VALUES (N'Parent Exempt', 0, 1, N'TDSAcc-ParentExempt', 0, 0)
INSERT TDS_TestToolType VALUES (N'Passage Font Size', 0, 0, N'TDSAcc-FontSize', 0, 0)
INSERT TDS_TestToolType VALUES (N'Periodic Table', 0, 0, N'TDSAcc-PeriodicTable', 0, 0)
INSERT TDS_TestToolType VALUES (N'Permissive Mode', 1, 1, N'TDSAcc-PermissiveMode', 0, 1)
INSERT TDS_TestToolType VALUES (N'Print on Request', 1, 1, N'TDSAcc-PrintOnRequest', 0, 1)
INSERT TDS_TestToolType VALUES (N'Print Size', 1, 1, N'TDSAcc-PrintSize', 1, 0)
INSERT TDS_TestToolType VALUES (N'Protractor', 1, 1, N'TDSAcc-Protractor', 0, 1)
INSERT TDS_TestToolType VALUES (N'Require Page Visit', 1, 0, N'TDSAcc-RequirePageVisit', 0, 0)
INSERT TDS_TestToolType VALUES (N'Rubrics', 1, 0, N'TDSAcc-Rubrics', 0, 0)
INSERT TDS_TestToolType VALUES (N'Ruler', 1, 1, N'TDSAcc-Ruler', 0, 1)
INSERT TDS_TestToolType VALUES (N'Scaffolding Voice Guidance', 1, 0, N'TDSAcc-ScaffoldingVoiceGuidance', 0, 0)
INSERT TDS_TestToolType VALUES (N'Straight Line', 1, 1, N'TDSAcc-StraightLine', 0, 1)
INSERT TDS_TestToolType VALUES (N'Strikethrough', 0, 0, N'TDSAcc-Strikethrough', 0, 0)
INSERT TDS_TestToolType VALUES (N'Student Comments', 0, 0, N'TDSAcc-StudentComments', 0, 0)
INSERT TDS_TestToolType VALUES (N'Suppress Score', 0, 1, N'TDSAcc-SuppressScore', 0, 1)
INSERT TDS_TestToolType VALUES (N'System Volume Control', 1, 0, N'TDSAcc-SVC', 0, 0)
INSERT TDS_TestToolType VALUES (N'TDSPoolFilter', 0, 1, N'--TBD--', 0, 1)
INSERT TDS_TestToolType VALUES (N'Test Progress Indicator', 1, 0, N'TDSAcc-TPI', 0, 0)
INSERT TDS_TestToolType VALUES (N'Test Shell', 1, 0, N'TDSAcc-TestShell', 0, 0)
INSERT TDS_TestToolType VALUES (N'Thesaurus', 1, 1, N'TDSAcc-Thesaurus', 0, 1)
INSERT TDS_TestToolType VALUES (N'Thesaurus Options', 1, 1, N'TDSAcc-ThesaurusOptns', 0, 1)
INSERT TDS_TestToolType VALUES (N'TTS', 1, 1, N'TDSAcc-TTS', 0, 1)
INSERT TDS_TestToolType VALUES (N'TTS Audio Adjustments', 1, 1, N'TDSAcc-TTSAdjust', 0, 1)
INSERT TDS_TestToolType VALUES (N'TTS Pausing', 1, 1, N'TDSAcc-TTSPausing', 0, 1)
INSERT TDS_TestToolType VALUES (N'TTS Tracking', 1, 0, N'TDSAcc-TTSTracking', 0, 0)
INSERT TDS_TestToolType VALUES (N'TTX Business Rules', 1, 1, N'TDSAcc-TTXBusinessRules', 0, 1)
INSERT TDS_TestToolType VALUES (N'Tutorial', 0, 0, N'TDSAcc-Tutorial', 0, 0)
INSERT TDS_TestToolType VALUES (N'Word List', 1, 1, N'TDSAcc-WordList', 0, 0)

INSERT TDS_TestTool VALUES (N'Audio Playback Controls', N'TDS_APC_PS', N'Play and Stop', 1, N'Play and Stop in a single button', 0, 1, 0)
INSERT TDS_TestTool VALUES (N'Audio Playback Controls', N'TDS_APC_PSP', N'Play Stop and Pause', 0, N'Play Stop Pause and rewind. Two buttons.', 0, 1, 1)
INSERT TDS_TestTool VALUES (N'Scaffolding Voice Guidance', N'TDS_ASIGuide0', N'Voice Guidance Off', 1, N'ASI items are presented without audio', 0, 1, 0)
INSERT TDS_TestTool VALUES (N'Scaffolding Voice Guidance', N'TDS_ASIGuide1', N'Voice Guidance On', 0, N'ASI items are presented with audio', 0, 1, 1)
INSERT TDS_TestTool VALUES (N'American Sign Language', N'TDS_ASL0', N'Do not show ASL videos', 1, N'Do not show ASL videos', 0, 1, -1)
INSERT TDS_TestTool VALUES (N'American Sign Language', N'TDS_ASL1', N'Show ASL videos', 0, N'Show ASL videos', 0, 1, 2)
INSERT TDS_TestTool VALUES (N'Block Pausing', N'TDS_BP0', N'Allow pausing anytime', 0, N'Allow pausing anytime', 0, 1, 2)
INSERT TDS_TestTool VALUES (N'Block Pausing', N'TDS_BP1', N'Block pausing with unanswered items', 1, N'Block pausing with unanswered items', 0, 1, 1)
INSERT TDS_TestTool VALUES (N'Braille', N'TDS_Braille0', N'False', 1, N'Braille feature is disabled', 0, 1, -1)
INSERT TDS_TestTool VALUES (N'Braille', N'TDS_Braille1', N'True', 0, N'Braille feature is enabled', 0, 1, 1)
INSERT TDS_TestTool VALUES (N'Braille Type', N'TDS_BT_G1', N'Uncontracted', 0, N'Uncontracted', 0, 1, 1)
INSERT TDS_TestTool VALUES (N'Braille Type', N'TDS_BT_G2', N'Contracted', 0, N'Contracted', 0, 1, 2)
INSERT TDS_TestTool VALUES (N'Braille Type', N'TDS_BT_NM', N'Nemeth', 0, N'Nemeth', 0, 1, 3)
INSERT TDS_TestTool VALUES (N'Braille Type', N'TDS_BT0', N'Not Applicable', 1, N'Not Applicable', 0, 1, -1)
INSERT TDS_TestTool VALUES (N'Calculator', N'TDS_Calc0', N'None', 1, N'Calculator feature is disabled', 0, 1, -1)
INSERT TDS_TestTool VALUES (N'Calculator', N'TDS_CalcBasic', N'Basic', 0, N'Basic Calculator is enabled', 1, 1, 1)
INSERT TDS_TestTool VALUES (N'Calculator', N'TDS_CalcGraphing', N'Graphing', 0, N'Graphing Calculator is enabled', 1, 1, 5)
INSERT TDS_TestTool VALUES (N'Calculator', N'TDS_CalcGraphingInv', N'Graphing with inverse trig', 0, N'Graphing calculator with inverse trig functions', 1, 1, 8)
INSERT TDS_TestTool VALUES (N'Calculator', N'TDS_CalcMatrices', N'Matrices', 0, N'Matrices Calculator is enabled', 1, 1, 6)
INSERT TDS_TestTool VALUES (N'Calculator', N'TDS_CalcRegress', N'Regressions', 0, N'Regressions Calculator is enabled', 1, 1, 7)
INSERT TDS_TestTool VALUES (N'Calculator', N'TDS_CalcSci', N'Scientific', 0, N'Scientific Calculator is enabled', 1, 1, 4)
INSERT TDS_TestTool VALUES (N'Calculator', N'TDS_CalcSciInv', N'Scientific with inverse trig', 0, N'Scientific calculator with inverse trig functions', 1, 1, 9)
INSERT TDS_TestTool VALUES (N'Calculator', N'TDS_CalcStd', N'Standard', 0, N'Standard Calculator is enabled', 1, 1, 2)
INSERT TDS_TestTool VALUES (N'Calculator', N'TDS_CalcStdMem', N'StandardMem', 0, N'Standard calc with enhanced memory keys', 1, 1, 3)
INSERT TDS_TestTool VALUES (N'Color Choices', N'TDS_CC0', N'None', 1, N'Color Choices feature is disabled', 0, 1, -1)
INSERT TDS_TestTool VALUES (N'Color Choices', N'TDS_CCBlue', N'Blue', 0, N'Blue', 0, 1, 2)
INSERT TDS_TestTool VALUES (N'Color Choices', N'TDS_CCBlue2', N'Light Blue', 0, N'Light Blue', 0, 1, 7)
INSERT TDS_TestTool VALUES (N'Color Choices', N'TDS_CCGray', N'Gray', 0, N'Gray', 0, 1, 10)
INSERT TDS_TestTool VALUES (N'Color Choices', N'TDS_CCGray2', N'Light Gray', 0, N'Light Gray', 0, 1, 11)
INSERT TDS_TestTool VALUES (N'Color Choices', N'TDS_CCGreen', N'Green', 0, N'Green', 0, 1, 12)
INSERT TDS_TestTool VALUES (N'Color Choices', N'TDS_CCGreen2', N'Light Green', 0, N'Light Green', 0, 1, 13)
INSERT TDS_TestTool VALUES (N'Color Choices', N'TDS_CCInvert', N'Inverted (White on Black)', 0, N'White text with a Black background', 0, 1, 15)
INSERT TDS_TestTool VALUES (N'Color Choices', N'TDS_CCMagenta', N'Magenta', 0, N'Magenta', 0, 1, 8)
INSERT TDS_TestTool VALUES (N'Color Choices', N'TDS_CCMagenta2', N'Light Magenta', 0, N'Light Magenta', 0, 1, 9)
INSERT TDS_TestTool VALUES (N'Color Choices', N'TDS_CCMedGrayLtGray', N'Medium Gray on Light Gray', 0, N'Medium Gray on Light Gray', 0, 1, 17)
INSERT TDS_TestTool VALUES (N'Color Choices', N'TDS_CCWhiteN', N'White on Navy', 0, N'White text with a Navy background', 0, 1, 16)
INSERT TDS_TestTool VALUES (N'Color Choices', N'TDS_CCYellow', N'Yellow', 0, N'Yellow', 0, 1, 1)
INSERT TDS_TestTool VALUES (N'Color Choices', N'TDS_CCYellow2', N'Light Yellow', 0, N'Light Yellow', 0, 1, 6)
INSERT TDS_TestTool VALUES (N'Color Choices', N'TDS_CCYellowB', N'Yellow on Blue', 0, N'Yellow text with a Blue background', 0, 1, 14)
INSERT TDS_TestTool VALUES (N'Closed Captioning', N'TDS_ClosedCap0', N'Closed Captioning Not Available', 1, N'Closed Captioning is off', 0, 1, -1)
INSERT TDS_TestTool VALUES (N'Closed Captioning', N'TDS_ClosedCap1', N'Closed Captioning Available', 0, N'Closed Captioning is on', 0, 1, 1)
INSERT TDS_TestTool VALUES (N'Compass', N'TDS_Compass0', N'Compass Off', 1, N'Compass Off', 0, 1, 1)
INSERT TDS_TestTool VALUES (N'Compass', N'TDS_Compass1', N'Compass On', 0, N'Compass On', 0, 1, 2)
INSERT TDS_TestTool VALUES (N'Cover Pages', N'TDS_CP_Z0', N'Disable Zooming', 0, N'Disable Zooming on Cover Pages', 0, 0, 1)
INSERT TDS_TestTool VALUES (N'Cover Pages', N'TDS_CP_Z1', N'Allow Zooming', 1, N'Allow Zooming on Cover Pages', 0, 0, 0)
INSERT TDS_TestTool VALUES (N'Dictionary', N'TDS_Dict_Collegiate', N'MerriamWebsters Collegiate Dictionary', 0, N'MerriamWebsters Collegiate Dictionary with Audio', 0, 1, 5)
INSERT TDS_TestTool VALUES (N'Dictionary', N'TDS_Dict_Learners', N'MerriamWebsters Learners Dictionary', 0, N'MerriamWebsters Learners Dictionary with Audio', 0, 1, 1)
INSERT TDS_TestTool VALUES (N'Dictionary', N'TDS_Dict_SD2', N'MerriamWebsters Elementary Dictionary', 0, N'MerriamWebsters Elementary Dictionary with Audio for Grades 3-5', 0, 1, 2)
INSERT TDS_TestTool VALUES (N'Dictionary', N'TDS_Dict_SD3', N'MerriamWebsters Intermediate Dictionary', 0, N'MerriamWebsters Intermediate Dictionary with Audio for Grades 6-8', 0, 1, 3)
INSERT TDS_TestTool VALUES (N'Dictionary', N'TDS_Dict_SD4', N'MerriamWebsters School Dictionary', 0, N'MerriamWebsters School Dictionary with Audio for Grades 9-11', 0, 1, 4)
INSERT TDS_TestTool VALUES (N'Dictionary', N'TDS_Dict0', N'Off', 1, N'None', 0, 1, 0)
INSERT TDS_TestTool VALUES (N'Dictionary Options', N'TDS_DO_ALL', N'All Options', 0, N'All Options', 0, 1, 1)
INSERT TDS_TestTool VALUES (N'Dictioanry Options', N'TDS_DO_EM', N'Exact matches', 0, N'Only show search results which are an exact match to the input', 1, 1, 7)
INSERT TDS_TestTool VALUES (N'Dictionary Options', N'TDS_DO_LB', N'Usage label', 0, N'LABEL for CAP or OFTEN ATTRIB or USAGE', 1, 1, 9)
INSERT TDS_TestTool VALUES (N'Dictionary Options', N'TDS_DO_LI', N'Linkify words', 0, N'Linkify relevant words in a selected entry', 1, 1, 6)
INSERT TDS_TestTool VALUES (N'Dictionary Options', N'TDS_DO_None', N'None', 1, N'None', 0, 1, 0)
INSERT TDS_TestTool VALUES (N'Dictionary Options', N'TDS_DO_PR', N'Pronunciation symbols', 0, N'Pronunciation symbols', 1, 1, 3)
INSERT TDS_TestTool VALUES (N'Dictionary Options', N'TDS_DO_SL', N'Audio pronunciations', 0, N'Audio pronunciations', 1, 1, 4)
INSERT TDS_TestTool VALUES (N'Dictionary Options', N'TDS_DO_SSL', N'Sense Subject or Status Label', 0, N'eg SLANG or ARCHAIC or OBSOLETE', 1, 1, 8)
INSERT TDS_TestTool VALUES (N'Dictionary Options', N'TDS_DO_VI', N'Examples', 0, N'Examples', 1, 1, 2)
INSERT TDS_TestTool VALUES (N'Dictionary Options', N'TDS_DO_WO', N'Word root and word history paragraphs', 0, N'Word root and word history paragraphs', 1, 1, 5)
INSERT TDS_TestTool VALUES (N'Emboss', N'TDS_Emboss_Item', N'Items', 0, N'Emboss Items', 1, 1, 2)
INSERT TDS_TestTool VALUES (N'Emboss', N'TDS_Emboss_Stim', N'Stimuli', 0, N'Emboss Stimuli', 1, 1, 1)
INSERT TDS_TestTool VALUES (N'Emboss', N'TDS_Emboss0', N'None', 1, N'Embossing is disabled', 0, 1, -1)
INSERT TDS_TestTool VALUES (N'Emboss Request Type', N'TDS_ERT_Auto', N'Auto-Request', 0, N'Auto-Request', 1, 1, 2)
INSERT TDS_TestTool VALUES (N'Emboss Request Type', N'TDS_ERT_OR', N'On-Request', 0, N'On-Request', 1, 1, 1)
INSERT TDS_TestTool VALUES (N'Emboss Request Type', N'TDS_ERT0', N'Not Applicable', 1, N'Not Applicable', 0, 1, -1)
INSERT TDS_TestTool VALUES (N'Exempted Domains', N'TDS_Exmpt_LI', N'Listening', 0, N'Exempt student from the Listening domain', 1, 1, 1)
INSERT TDS_TestTool VALUES (N'Exempted Domains', N'TDS_Exmpt_RE', N'Reading', 0, N'Exempt student from the Reading domain', 1, 1, 2)
INSERT TDS_TestTool VALUES (N'Exempted Domains', N'TDS_Exmpt_SP', N'Speaking', 0, N'Exempt student from the Speaking domain', 1, 1, 3)
INSERT TDS_TestTool VALUES (N'Exempted Domains', N'TDS_Exmpt_WR', N'Writing', 0, N'Exempt student from the Writing domain', 1, 1, 4)
INSERT TDS_TestTool VALUES (N'Exempted Domains', N'TDS_Exmpt0', N'No Exemptions', 1, N'No domain exemptions', 0, 1, -1)
INSERT TDS_TestTool VALUES (N'Expandable Passages', N'TDS_ExpandablePassages0', N'Expandable Passages Off', 1, N'No expanding passages', 0, 1, 1)
INSERT TDS_TestTool VALUES (N'Expandable Passages', N'TDS_ExpandablePassages1', N'Expandable Passages On', 0, N'Allow student to expand/collapse passages', 0, 1, 2)
INSERT TDS_TestTool VALUES (N'Formula', N'TDS_F_AR_3_5Math', N'AIR 3-5 Math', 0, N'AIR 3-5 Math', 0, 1, 32)
INSERT TDS_TestTool VALUES (N'Formula', N'TDS_F_AR_6_8Math', N'AIR 6-8 Math', 0, N'AIR 6-8 Math', 0, 0, 33)
INSERT TDS_TestTool VALUES (N'Formula', N'TDS_F_AR_9_10Math', N'AIR 9-10 Math', 0, N'AIR 9-10 Math', 0, 0, 34)
INSERT TDS_TestTool VALUES (N'Formula', N'TDS_F_DE_2Math', N'DE 2 Math', 0, N'DE 2 Math', 0, 1, 1)
INSERT TDS_TestTool VALUES (N'Formula', N'TDS_F_DE_6_8Math', N'DE 6-8 Math', 0, N'DE 6-8 Math', 0, 1, 2)
INSERT TDS_TestTool VALUES (N'Formula', N'TDS_F_DE_9_10Math', N'DE 9-10 Math', 0, N'DE 9-10 Math', 0, 1, 3)
INSERT TDS_TestTool VALUES (N'Formula', N'TDS_F_DE_EOC2Math', N'DE EOC2 Math', 0, N'DE EOC2 Math', 0, 1, 4)
INSERT TDS_TestTool VALUES (N'Formula', N'TDS_F_HI_10Math', N'HI 10 Math', 0, N'HI 10 Math', 0, 1, 10)
INSERT TDS_TestTool VALUES (N'Formula', N'TDS_F_HI_11Sci', N'HI 11 Science', 0, N'HI 11 Science', 0, 1, 11)
INSERT TDS_TestTool VALUES (N'Formula', N'TDS_F_HI_4Math', N'HI 4 Math', 0, N'HI 4 Math', 0, 1, 12)
INSERT TDS_TestTool VALUES (N'Formula', N'TDS_F_HI_5Math', N'HI 5 Math', 0, N'HI 5 Math', 0, 1, 13)
INSERT TDS_TestTool VALUES (N'Formula', N'TDS_F_HI_6Math', N'HI 6 Math', 0, N'HI 6 Math', 0, 1, 14)
INSERT TDS_TestTool VALUES (N'Formula', N'TDS_F_HI_7Math', N'HI 7 Math', 0, N'HI 7 Math', 0, 1, 15)
INSERT TDS_TestTool VALUES (N'Formula', N'TDS_F_HI_8Math', N'HI 8 Math', 0, N'HI 8 Math', 0, 1, 16)
INSERT TDS_TestTool VALUES (N'Formula', N'TDS_F_HI_AlgII', N'HI EOC AlgII', 0, N'HI EOC AlgII', 0, 1, 35)
INSERT TDS_TestTool VALUES (N'Formula', N'TDS_F_MN_11Math', N'MN 11 Math', 0, N'MN 11 Math', 0, 1, 20)
INSERT TDS_TestTool VALUES (N'Formula', N'TDS_F_MN_5Math', N'MN 5 Math', 0, N'MN 5 Math', 0, 1, 21)
INSERT TDS_TestTool VALUES (N'Formula', N'TDS_F_MN_6Math', N'MN 6 Math', 0, N'MN 6 Math', 0, 1, 22)
INSERT TDS_TestTool VALUES (N'Formula', N'TDS_F_MN_7Math', N'MN 7 Math', 0, N'MN 7 Math', 0, 1, 23)
INSERT TDS_TestTool VALUES (N'Formula', N'TDS_F_MN_8Math', N'MN 8 Math', 0, N'MN 8 Math', 0, 1, 24)
INSERT TDS_TestTool VALUES (N'Formula', N'TDS_F_MN_GRADMath', N'MN GRAD Math', 0, N'MN GRAD Math', 0, 1, 25)
INSERT TDS_TestTool VALUES (N'Formula', N'TDS_F_OH_HS_Physics', N'OH HS Physics', 0, N'OH HS Physics', 0, 1, 36)
INSERT TDS_TestTool VALUES (N'Formula', N'TDS_F_OR3_5', N'OR 3-5 Math', 0, N'OR 3-5 Math', 0, 1, 30)
INSERT TDS_TestTool VALUES (N'Formula', N'TDS_F_ORCIM_Math', N'OR CIM Math', 0, N'OR CIM Math', 0, 1, 32)
INSERT TDS_TestTool VALUES (N'Passage Font Size', N'TDS_F_S12', N'12pt', 1, N'Font Size is set to 12pt', 0, 1, -1)
INSERT TDS_TestTool VALUES (N'Passage Font Size', N'TDS_F_S14', N'14pt', 0, N'Font Size is set to 14pt', 0, 1, 1)
INSERT TDS_TestTool VALUES (N'Formula', N'TDS_F_UT_HS_Physics', N'UT HS Physics', 0, N'UT HS Physics', 0, 1, 37)
INSERT TDS_TestTool VALUES (N'Formula', N'TDS_F_UT_HS_PT', N'UT Custom Periodic Table', 0, N'UT custom per tab', 0, 0, 39)
INSERT TDS_TestTool VALUES (N'Formula', N'TDS_F_UT_HS_Science', N'UT HS Science', 0, N'UT HS Science', 0, 1, 38)
INSERT TDS_TestTool VALUES (N'Formula', N'TDS_F0', N'None', 1, N'Formula is not available', 0, 1, -1)
INSERT TDS_TestTool VALUES (N'Formula', N'TDS_FOR6_8Math', N'OR 6-8 Math', 0, N'OR 6-8 Math', 0, 1, 31)
INSERT TDS_TestTool VALUES (N'Fullscreen', N'TDS_FS_Off', N'Fullscreen toggle not available', 1, N'Fullscreen toggle not available', 0, 1, 0)
INSERT TDS_TestTool VALUES (N'Fullscreen', N'TDS_FS_On', N'Fullscreen toggle available', 0, N'Fullscreen toggle available.  Does not require password.  Not fullscreen automatically.', 0, 1, 1)
INSERT TDS_TestTool VALUES (N'Fullscreen', N'TDS_FS_Pass', N'Fullscreen with password', 0, N'Fullscreen toggle available.  Requires Password.  Automatically fullscreen.', 0, 1, 2)
INSERT TDS_TestTool VALUES (N'Font Type', N'TDS_FT_CenturyGothic', N'Century Gothic', 0, N'Font Type is set to Century Gothic', 0, 1, 3)
INSERT TDS_TestTool VALUES (N'Font Type', N'TDS_FT_San-Serif', N'San-Serif (Arial)', 1, N'Font Type is set to San-Serif (Arial)', 0, 1, -1)
INSERT TDS_TestTool VALUES (N'Font Type', N'TDS_FT_Serif', N'Serif (Times)', 0, N'Font Type is set to Serif (Times)', 0, 1, 1)
INSERT TDS_TestTool VALUES (N'Font Type', N'TDS_FT_Verdana', N'Verdana', 0, N'Font Type is set to Verdana', 0, 1, 2)
INSERT TDS_TestTool VALUES (N'Guide for Revision', N'TDS_GfR0', N'False', 1, N'Guide for Revision feature is disabled', 0, 1, -1)
INSERT TDS_TestTool VALUES (N'Guide for Revision', N'TDS_GfR1', N'True', 0, N'Guide for Revision  feature is enabled', 0, 1, 1)
INSERT TDS_TestTool VALUES (N'Global Notes', N'TDS_GN0', N'Global Notes Off', 1, N'Global Notes Off', 0, 1, -1)
INSERT TDS_TestTool VALUES (N'Global Notes', N'TDS_GN1', N'Global Notes On', 0, N'Global Notes On', 0, 1, 1)
INSERT TDS_TestTool VALUES (N'Highlight', N'TDS_Highlight0', N'False', 1, N'Highlight feature is disabled', 0, 1, -1)
INSERT TDS_TestTool VALUES (N'Highlight', N'TDS_Highlight1', N'True', 0, N'Highlight  feature is enabled', 0, 1, 1)
INSERT TDS_TestTool VALUES (N'Hardware Checks', N'TDS_HW0', N'No hardware checks will be done', 1, N'No hardware checks will be done', 0, 1, 1)
INSERT TDS_TestTool VALUES (N'Hardware Checks', N'TDS_HWPlayback', N'Check Playback Capabilities', 0, N'Check Playback Capabilies', 1, 1, 3)
INSERT TDS_TestTool VALUES (N'Hardware Checks', N'TDS_HWRecording', N'Check Recording Capabilities', 0, N'Check Recording Capabilies', 1, 1, 2)
INSERT TDS_TestTool VALUES (N'Item Font Size', N'TDS_IF_S12', N'12pt Items', 1, N'Item Font Size is set to 12pt', 0, 1, 0)
INSERT TDS_TestTool VALUES (N'Item Font Size', N'TDS_IF_S14', N'14pt Items', 0, N'Item Font Size is set to 14pt', 0, 1, 1)
INSERT TDS_TestTool VALUES (N'Item Score Report', N'TDS_ISR_Summary', N'Show Item Score Summary', 0, N'Show a table at the end of the test summarizing the score for each item', 0, 1, 2)
INSERT TDS_TestTool VALUES (N'Item Score Report', N'TDS_ISR_SumViewResp', N'Summarize Scores And Allow Viewing Responses', 0, N'Show a table at the end of the test summarizing the score for each item and allow the option to go back and see their response', 0, 1, 3)
INSERT TDS_TestTool VALUES (N'Item Score Report', N'TDS_ISR0', N'None', 1, N'No Item Score Report', 0, 1, 1)
INSERT TDS_TestTool VALUES (N'Item Response Reset', N'TDS_ItemReset0', N'Resetting Responses Off', 0, N'User not allowed to reset item responses', 0, 1, 1)
INSERT TDS_TestTool VALUES (N'Item Response Reset', N'TDS_ItemReset1', N'Allow Resetting Responses', 1, N'Allow users to reset item responses', 0, 1, 2)
INSERT TDS_TestTool VALUES (N'Item Types Exclusion', N'TDS_ItemTypeExcl_GI', N'Grid Items', 0, N'Grid Items', 1, 0, 1)
INSERT TDS_TestTool VALUES (N'Item Types Exclusion', N'TDS_ItemTypeExcl_NL', N'NL Items', 0, N'NL Items', 1, 0, 1)
INSERT TDS_TestTool VALUES (N'Item Types Exclusion', N'TDS_ItemTypeExcl_None', N'None', 1, N'None', 0, 0, -1)
INSERT TDS_TestTool VALUES (N'Item Numbers', N'TDS_ItmNum0', N'Do Not Show', 0, N'Do not show numbers next to items', 0, 1, 1)
INSERT TDS_TestTool VALUES (N'Item Numbers', N'TDS_ItmNumPos', N'Show Position Numbers', 1, N'So the item position number on the test', 0, 1, -1)
INSERT TDS_TestTool VALUES (N'Item Numbers', N'TDS_ItmNumSeq', N'Show Group Sequence Numbers', 0, N'Restart numbering items on every page', 0, 1, 2)
INSERT TDS_TestTool VALUES (N'Line Reader', N'TDS_LR0', N'Line Reader Off', 1, N'Line Reader Off', 0, 1, 0)
INSERT TDS_TestTool VALUES (N'Line Reader', N'TDS_LR1', N'Line Reader On', 0, N'Line Reader On', 0, 1, 1)
INSERT TDS_TestTool VALUES (N'Masking', N'TDS_Masking0', N'Masking Not Available', 1, N'Masking is off', 0, 1, -1)
INSERT TDS_TestTool VALUES (N'Masking', N'TDS_Masking1', N'Masking Available', 0, N'Masking is on', 0, 1, 1)
INSERT TDS_TestTool VALUES (N'Mark for Review', N'TDS_MfR0', N'False', 1, N'Mark for Review feature is disabled', 0, 1, -1)
INSERT TDS_TestTool VALUES (N'Mark for Review', N'TDS_MfR1', N'True', 0, N'Mark for Review  feature is enabled', 0, 1, 1)
INSERT TDS_TestTool VALUES (N'Mute System Volume', N'TDS_Mute0', N'Not Muted', 1, N'System is NOT muted', 0, 1, 1)
INSERT TDS_TestTool VALUES (N'Mute System Volume', N'TDS_Mute1', N'Muted', 0, N'System IS muted', 0, 1, 2)
INSERT TDS_TestTool VALUES (N'Navigation Dropdown', N'TDS_Nav0', N'No Dropdown', 0, N'Drop-down is not available', 0, 1, -1)
INSERT TDS_TestTool VALUES (N'Navigation Dropdown', N'TDS_NavPg', N'Show Page Numbers', 0, N'Show Page Numbers', 0, 1, -1)
INSERT TDS_TestTool VALUES (N'Navigation Dropdown', N'TDS_NavQu', N'Show Question Numbers', 1, N'Show Question Numbers', 0, 1, -1)
INSERT TDS_TestTool VALUES (N'Navigation Dropdown', N'TDS_NavTk', N'Show Task Numbers', 0, N'Show Page Numbers', 0, 1, -1)
INSERT TDS_TestTool VALUES (N'Offline Tester', N'TDS_OfflineTester0', N'N', 1, N'Student is administered all tests online', 0, 1, -1)
INSERT TDS_TestTool VALUES (N'Offline Tester', N'TDS_OfflineTester1', N'Y', 0, N'Student is administered a paper version.  Responses entered in the online system later.', 0, 1, 1)
INSERT TDS_TestTool VALUES (N'Parent Exempt', N'TDS_ParentExempt0', N'False', 1, N'Student is allowed to take online tests', 0, 0, -1)
INSERT TDS_TestTool VALUES (N'Parent Exempt', N'TDS_ParentExempt1', N'True', 0, N'Student is not permitted to take online tests', 0, 0, 1)
INSERT TDS_TestTool VALUES (N'Paginate Item Groups', N'TDS_PIG0', N'Off', 1, N'Pagination is turned off', 0, 1, 0)
INSERT TDS_TestTool VALUES (N'Paginate Item Groups', N'TDS_PIG1', N'On', 0, N'Pagination is turned on', 0, 1, 1)
INSERT TDS_TestTool VALUES (N'Permissive Mode', N'TDS_PM0', N'Permissive Mode Disabled', 1, N'Permissive Mode Disabled', 0, 1, 0)
INSERT TDS_TestTool VALUES (N'Permissive Mode', N'TDS_PM1', N'Permissive Mode Enabled', 0, N'Permissive Mode Enabled', 0, 1, 1)
INSERT TDS_TestTool VALUES (N'Print on Request', N'TDS_PoD_Item', N'Items', 0, N'Print on Request enabled for items', 1, 1, 2)
INSERT TDS_TestTool VALUES (N'Print on Request', N'TDS_PoD_Stim', N'Stimuli', 0, N'Print on Request enabled for stimuli', 1, 1, 1)
INSERT TDS_TestTool VALUES (N'Print on Request', N'TDS_PoD0', N'None', 1, N'Print on Request feature is disabled', 0, 1, -1)
INSERT TDS_TestTool VALUES (N'Protractor', N'TDS_Protractor0', N'Protractor Off', 1, N'Do not show the button for the Protractor', 0, 1, 1)
INSERT TDS_TestTool VALUES (N'Protractor', N'TDS_Protractor1', N'Protractor On', 0, N'Show the button for the Protractor', 0, 1, 2)
INSERT TDS_TestTool VALUES (N'Print Size', N'TDS_PS_L0', N'No default zoom applied', 1, N'There is no default zoom', 0, 1, -1)
INSERT TDS_TestTool VALUES (N'Print Size', N'TDS_PS_L1', N'Level 1', 0, N'Default level of zoom is set to 1', 0, 1, 1)
INSERT TDS_TestTool VALUES (N'Print Size', N'TDS_PS_L2', N'Level 2', 0, N'Default level of zoom is set to 2', 0, 1, 2)
INSERT TDS_TestTool VALUES (N'Print Size', N'TDS_PS_L3', N'Level 3', 0, N'Default level of zoom is set to 3', 0, 1, 3)
INSERT TDS_TestTool VALUES (N'Print Size', N'TDS_PS_L4', N'Level 4', 0, N'Default level of zoom is set to 4', 0, 1, 4)
INSERT TDS_TestTool VALUES (N'Periodic Table', N'TDS_PT_Basic', N'Basic', 0, N'DE and HI Basic', 0, 1, 2)
INSERT TDS_TestTool VALUES (N'Periodic Table', N'TDS_PT_Expanded', N'Expanded', 0, N'DE and HI Basic', 0, 1, 3)
INSERT TDS_TestTool VALUES (N'Periodic Table', N'TDS_PT_HTML', N'HTML', 0, N'Default HTML Periodic Table', 0, 1, 1)
INSERT TDS_TestTool VALUES (N'Periodic Table', N'TDS_PT_HTMLv2', N'HTML v2', 0, N'HTML Periodic Table v2', 0, 1, 4)
INSERT TDS_TestTool VALUES (N'Periodic Table', N'TDS_PT0', N'None', 1, N'Periodic Table is not available', 0, 1, -1)
INSERT TDS_TestTool VALUES (N'Rubrics', N'TDS_R_G35Argue', N'Utah G3to5 Argumentative', 0, N'Utah G3to5 Argumentative', 0, 1, 1)
INSERT TDS_TestTool VALUES (N'Rubrics', N'TDS_R_G35Inform', N'Utah G3to5 Informative', 0, N'Utah G3to5 Informative', 0, 1, 2)
INSERT TDS_TestTool VALUES (N'Rubrics', N'TDS_R_G68Argue', N'Utah G6to8 Argumentative', 0, N'Utah G6to8 Argumentative', 0, 1, 3)
INSERT TDS_TestTool VALUES (N'Rubrics', N'TDS_R_G68Inform', N'Utah G6to8 Informative', 0, N'Utah G6to8 Informative', 0, 1, 4)
INSERT TDS_TestTool VALUES (N'Rubrics', N'TDS_R_G911Argue', N'Utah G9to11 Argumentative', 0, N'Utah G9to11 Argumentative', 0, 1, 5)
INSERT TDS_TestTool VALUES (N'Rubrics', N'TDS_R_G911Inform', N'Utah G9to11 Informative', 0, N'Utah G9to11 Informative', 0, 1, 6)
INSERT TDS_TestTool VALUES (N'Rubrics', N'TDS_R0', N'None', 1, N'Do not show a human readable rubric to the student', 0, 1, 0)
INSERT TDS_TestTool VALUES (N'Require Page Visit', N'TDS_RPV0', N'False', 1, N'Allows a student to skip optional item groups without ever looking at them', 0, 1, 1)
INSERT TDS_TestTool VALUES (N'Require Page Visit', N'TDS_RPV1', N'True', 0, N'Require a student to visit every single group on the test regardless of item requirements', 0, 1, 2)
INSERT TDS_TestTool VALUES (N'Ruler', N'TDS_Ruler0', N'Ruler Off', 1, N'Do not show the button for the ruler', 0, 1, 1)
INSERT TDS_TestTool VALUES (N'Ruler', N'TDS_Ruler1', N'Ruler On', 0, N'Show the button for the ruler', 0, 1, 2)
INSERT TDS_TestTool VALUES (N'Student Comments', N'TDS_SC0', N'None', 1, N'Student comments feature is disabled', 0, 1, -1)
INSERT TDS_TestTool VALUES (N'Student Comments', N'TDS_SCDropDown', N'DropDown', 0, N'Student comments rendered as dropdown', 0, 1, 3)
INSERT TDS_TestTool VALUES (N'Student Comments', N'TDS_SCNotepad', N'Notepad', 0, N'Students comments rendered as a notepad', 0, 1, 2)
INSERT TDS_TestTool VALUES (N'Student Comments', N'TDS_SCTextArea', N'TextArea', 0, N'Student comments rendered as a textarea', 0, 1, 1)
INSERT TDS_TestTool VALUES (N'Suppress Score', N'TDS_SS0', N'Display score to student', 1, N'Display score to student', 0, 1, -1)
INSERT TDS_TestTool VALUES (N'Suppress Score', N'TDS_SS1', N'Do not display score to student', 0, N'Do not display score to student', 0, 1, 1)
INSERT TDS_TestTool VALUES (N'Strikethrough', N'TDS_ST0', N'False', 1, N'Strikethrough feature is disabled', 0, 1, -1)
INSERT TDS_TestTool VALUES (N'Strikethrough', N'TDS_ST1', N'True', 0, N'Strikethrough  feature is enabled', 0, 1, 1)
INSERT TDS_TestTool VALUES (N'Straight Line', N'TDS_StraightLine0', N'StraightLine Off', 1, N'StraightLine Off', 0, 1, 1)
INSERT TDS_TestTool VALUES (N'Straight Line', N'TDS_StraightLine1', N'StraightLine On', 0, N'StraightLine On', 0, 1, 2)
INSERT TDS_TestTool VALUES (N'System Volume Control', N'TDS_SVC0', N'Do not show widget', 1, N'Dont show volume control widget', 0, 0, 0)
INSERT TDS_TestTool VALUES (N'System Volume Control', N'TDS_SVC1', N'Show widget', 0, N'allow student to change the volume', 0, 0, 1)
INSERT TDS_TestTool VALUES (N'Tutorial', N'TDS_T0', N'False', 1, N'Tutorial feature is disabled', 0, 1, -1)
INSERT TDS_TestTool VALUES (N'Tutorial', N'TDS_T1', N'True', 0, N'Tutorial  feature is enabled', 0, 1, 1)
INSERT TDS_TestTool VALUES (N'Thesaurus', N'TDS_TH_TA', N'MerriamWebsters Collegiate Thesaurus', 0, N'MW Thesaurus On', 0, 1, 1)
INSERT TDS_TestTool VALUES (N'Thesaurus', N'TDS_TH0', N'Off', 1, N'Thesaurus Off', 0, 1, 0)
INSERT TDS_TestTool VALUES (N'Thesaurus Options', N'TDS_TO_ALL', N'All Options', 0, N'All Options MW Offers', 0, 1, 1)
INSERT TDS_TestTool VALUES (N'Thesaurus Options', N'TDS_TO_LI', N'Linkify words', 0, N'Synonyms', 1, 1, 2)
INSERT TDS_TestTool VALUES (N'Thesaurus Options', N'TDS_TO_None', N'None', 1, N'None', 0, 1, 0)
INSERT TDS_TestTool VALUES (N'Test Progress Indicator', N'TDS_TPI_None', N'Hide test progress indicator', 0, N'Hide test progress indicator', 0, 0, 0)
INSERT TDS_TestTool VALUES (N'Test Progress Indicator', N'TDS_TPI_Percent', N'Show indicator as a percentage and adjust to test length', 0, N'Show indicator as a percentage and adjust to test length', 0, 0, 3)
INSERT TDS_TestTool VALUES (N'Test Progress Indicator', N'TDS_TPI_Responses', N'Show indicator as a fraction', 0, N'Show indicator as a fraction', 0, 0, 1)
INSERT TDS_TestTool VALUES (N'Test Progress Indicator', N'TDS_TPI_ResponsesFix', N'Show indicator as a fraction and adjust to test length', 1, N'Show indicator as a fraction and adjust to test length', 0, 0, 2)
INSERT TDS_TestTool VALUES (N'Test Shell', N'TDS_TS_Accessibility', N'Streamlined Test Shell', 0, N'Accessibility Shell', 0, 1, 2)
INSERT TDS_TestTool VALUES (N'Test Shell', N'TDS_TS_Classic', N'Classic Test Shell', 1, N'Classic Test Shell', 0, 1, -1)
INSERT TDS_TestTool VALUES (N'Test Shell', N'TDS_TS_Modern', N'Tablet Compatible Test Shell', 0, N'Modern Shell with Cross Browser and Tablet Compatibility', 0, 1, 1)
INSERT TDS_TestTool VALUES (N'TTS', N'TDS_TTS_Inst', N'Instructions', 0, N'Text-to-speech is enabled on instructions', 1, 1, 1)
INSERT TDS_TestTool VALUES (N'TTS', N'TDS_TTS_Item', N'Items', 0, N'Text-to-speech is enabled on items', 1, 1, 3)
INSERT TDS_TestTool VALUES (N'TTS', N'TDS_TTS_NonItemPages', N'Non-Item Pages', 0, N'Text-to-speech is enabled on pages before and after the test shell', 1, 1, 4)
INSERT TDS_TestTool VALUES (N'TTS', N'TDS_TTS_Stim', N'Stimuli', 0, N'Text-to-speech is enabled on stimuli', 1, 1, 2)
INSERT TDS_TestTool VALUES (N'TTS', N'TDS_TTS0', N'None', 1, N'TTS feature is disabled', 0, 1, -1)
INSERT TDS_TestTool VALUES (N'TTS Audio Adjustments', N'TDS_TTSAA_Pitch', N'Allow TTS Pitch Adjustments', 0, N'Allow TTS Pitch Adjustments', 1, 1, 3)
INSERT TDS_TestTool VALUES (N'TTS Audio Adjustments', N'TDS_TTSAA_Rate', N'Allow TTS Rate Adjustments', 0, N'Allow TTS Rate Adjustments', 1, 1, 4)
INSERT TDS_TestTool VALUES (N'TTS Audio Adjustments', N'TDS_TTSAA_SelectVP', N'Allow Voice Pack Selection', 0, N'Allow Voice Pack Selection', 1, 1, 5)
INSERT TDS_TestTool VALUES (N'TTS Audio Adjustments', N'TDS_TTSAA_Volume', N'Allow TTS Volume Adjustments', 0, N'Allow TTS Volume Adjustments', 1, 1, 2)
INSERT TDS_TestTool VALUES (N'TTS Audio Adjustments', N'TDS_TTSAA0', N'TTS Audio Adjustments Off', 1, N'TTS Audio Adjustments Off', 0, 1, 1)
INSERT TDS_TestTool VALUES (N'TTS Pausing', N'TDS_TTSPause0', N'TTS Pausing Off', 1, N'TTS Pausing Off', 0, 1, 1)
INSERT TDS_TestTool VALUES (N'TTS Pausing', N'TDS_TTSPause1', N'TTS Pausing On', 0, N'TTS Pausing On', 0, 1, 2)
INSERT TDS_TestTool VALUES (N'TTS Tracking', N'TDS_TTSTracking0', N'Tracking Off', 1, N'Tracking Off', 0, 1, 0)
INSERT TDS_TestTool VALUES (N'TTS Tracking', N'TDS_TTSTracking1', N'Tracking On', 0, N'Tracking On', 0, 1, 1)
INSERT TDS_TestTool VALUES (N'TTX Business Rules', N'TDS_TTX_0', N'Read As-Is', 1, N'Read As-Is', 0, 1, -1)
INSERT TDS_TestTool VALUES (N'TTX Business Rules', N'TDS_TTX_A202', N'A202', 0, N'A202', 0, 1, 1)
INSERT TDS_TestTool VALUES (N'TTX Business Rules', N'TDS_TTX_A203', N'A203', 0, N'A203', 0, 1, 2)
INSERT TDS_TestTool VALUES (N'TTX Business Rules', N'TDS_TTX_A204', N'A204', 0, N'A204', 0, 1, 4)
INSERT TDS_TestTool VALUES (N'TTX Business Rules', N'TDS_TTX_A205', N'A205', 0, N'A205', 0, 1, 5)
INSERT TDS_TestTool VALUES (N'TTX Business Rules', N'TDS_TTX_A206', N'A206', 0, N'A206', 0, 1, 12)
INSERT TDS_TestTool VALUES (N'TTX Business Rules', N'TDS_TTX_HI101', N'HI101', 0, N'HI101', 0, 1, 8)
INSERT TDS_TestTool VALUES (N'TTX Business Rules', N'TDS_TTX_HI102', N'HI102', 0, N'HI102', 0, 1, 9)
INSERT TDS_TestTool VALUES (N'TTX Business Rules', N'TDS_TTX_M101', N'M101', 0, N'M101', 0, 1, 6)
INSERT TDS_TestTool VALUES (N'TTX Business Rules', N'TDS_TTX_M102', N'M102', 0, N'M102', 0, 1, 7)
INSERT TDS_TestTool VALUES (N'TTX Business Rules', N'TDS_TTX_U101', N'U101', 0, N'U101', 0, 0, 10)
INSERT TDS_TestTool VALUES (N'TTX Business Rules', N'TDS_TTX_U102', N'U102', 0, N'U102', 0, 0, 11)
INSERT TDS_TestTool VALUES (N'Word List', N'TDS_WL_ArabicGloss', N'Arabic Glossary', 0, N'Arabic Glossary is Available', 1, 1, 5)
INSERT TDS_TestTool VALUES (N'Word List', N'TDS_WL_CantoneseGloss', N'Cantonese Glossary', 0, N'Cantonese Glossary is Available', 1, 1, 7)
INSERT TDS_TestTool VALUES (N'Word List', N'TDS_WL_DICT', N'Dictionary', 0, N'Dictionary is available', 1, 1, 3)
INSERT TDS_TestTool VALUES (N'Word List', N'TDS_WL_ESNGlossary', N'Spanish Glossary', 0, N'Spanish Glossary is Available', 1, 1, 2)
INSERT TDS_TestTool VALUES (N'Word List', N'TDS_WL_Glossary', N'Glossary', 0, N'Glossary is Available', 1, 1, 1)
INSERT TDS_TestTool VALUES (N'Word List', N'TDS_WL_KoreanGloss', N'Korean Glossary', 0, N'Korean Glossary is Available', 1, 1, 11)
INSERT TDS_TestTool VALUES (N'Word List', N'TDS_WL_MandarinGloss', N'Mandarin Glossary', 0, N'Mandarin Glossary is Available', 1, 1, 8)
INSERT TDS_TestTool VALUES (N'Word List', N'TDS_WL_PunjabiGloss', N'Punjabi Glossary', 0, N'Punjabi Glossary is Available', 1, 1, 12)
INSERT TDS_TestTool VALUES (N'Word List', N'TDS_WL_RussianGloss', N'Russian Glossary', 0, N'Russian Glossary is Available', 1, 1, 10)
INSERT TDS_TestTool VALUES (N'Word List', N'TDS_WL_TagalGloss', N'Tagal Glossary', 0, N'Tagal Glossary is Available', 1, 1, 9)
INSERT TDS_TestTool VALUES (N'Word List', N'TDS_WL_THES', N'Thesaurus', 0, N'Thesaurus is available', 1, 1, 4)
INSERT TDS_TestTool VALUES (N'Word List', N'TDS_WL_UkrainianGloss', N'Ukrainian Glossary', 0, N'Ukrainian Glossary is Available', 1, 1, 13)
INSERT TDS_TestTool VALUES (N'Word List', N'TDS_WL_VietnameseGloss', N'Vietnamese Glossary', 0, N'Vietnamese Glossary is Available', 1, 1, 6)
INSERT TDS_TestTool VALUES (N'Word List', N'TDS_WL0', N'No Word List Available', 1, N'No Word List Available', 0, 1, -1)

