/*******************************************************************************
* Educational Online Test Delivery System
* Copyright (c) 2014 American Institutes for Research
*
* Distributed under the AIR Open Source License, Version 1.0
* See accompanying file AIR-License-1_0.txt or at
* http://www.smarterapp.org/documents/American_Institutes_for_Research_Open_Source_Software_License.pdf
******************************************************************************/
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace TDS.ItemScoringEngine
{
    /// <summary>
    /// Interface used for implementations of a specific item type scorer. 
    /// </summary>
    public interface IItemScorer
    {
        /// <summary>
        /// Retrieve meta-information about this scorer implementation
        /// </summary>
        /// <param name="itemFormat">Format for item. Only useful when a single itemScorer can score multiple formats</param>
        /// <returns> Meta-info about the scorer implementation</returns>
        ScorerInfo GetScorerInfo(string itemFormat);

        /// <summary>
        /// Main method for this interface to score a student's response
        /// </summary>        
        /// <param name="ResponseInfo">Rubric/Response struct information for the scoring engine</param>        
        /// <param name="callback">Handler to be invoked when the scoring engine has completed async scoring</param>
        /// <returns>Score generated by the scoring engine. This can be a final score (sync mode) or an interim score (async mode)</returns>
        ItemScore ScoreItem(ResponseInfo responseInfo, IItemScorerCallback callback);

    }
}
