//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TDSQASystemAPI.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=38.118.82.146;Initial Catalog=TDS_QC_;Persist Security Info=True;User" +
            " ID=dbtds;Password=KOJ89238876234rUHJ")]
        public string TDS_QC_ConnectionString {
            get {
                return ((string)(this["TDS_QC_ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=38.118.82.146;Initial Catalog=TDS_QC_MN_2011;Integrated Security=True" +
            "")]
        public string TDS_QC_MN_2011ConnectionString {
            get {
                return ((string)(this["TDS_QC_MN_2011ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=38.118.82.146;Initial Catalog=TDS_QC_DE_2013;User ID=dbtds")]
        public string TDS_QC_DE_2012ConnectionString {
            get {
                return ((string)(this["TDS_QC_DE_2012ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=38.118.82.146;Initial Catalog=TDS_QC_DE_2011;Integrated Security=True" +
            "")]
        public string TDS_QC_DE_2011ConnectionString {
            get {
                return ((string)(this["TDS_QC_DE_2011ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=38.118.82.146;Initial Catalog=TDS_QC_OR_2012;Integrated Security=True" +
            "")]
        public string TDS_QC_OR_2012ConnectionString {
            get {
                return ((string)(this["TDS_QC_OR_2012ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://38.118.83.42/webservice/XMLLoaderService.asmx")]
        public string TDSQASystemAPI_UpdateDoR_Service {
            get {
                return ((string)(this["TDSQASystemAPI_UpdateDoR_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=38.118.82.146;Initial Catalog=TDS_QC_DE;Integrated Security=True")]
        public string TDS_QC_DEConnectionString {
            get {
                return ((string)(this["TDS_QC_DEConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=38.118.82.146;Initial Catalog=TDS_QC_MN_2013;Integrated Security=True" +
            "")]
        public string TDS_QC_MN_2013ConnectionString {
            get {
                return ((string)(this["TDS_QC_MN_2013ConnectionString"]));
            }
        }
    }
}
